export const BASIC_FEATURES = [
  'Calculator Billing',
  'Vendor POS Dashboard Access',
  'Total Sale Board',
  'Automated Sales Reports',
  'Custom Voucher Numbering',
  'Autofill Bill Amount & Balances',
  'Daily Performance Board',
  'Payment Methods Board',
  'Hide Data Functionality',
  'Amount vs Quantity in Boards',
  'Transaction filter & search',
  'Automated business card making',
];

export const PRO_FEATURES = [
  ...BASIC_FEATURES.filter(f => f !== 'Calculator Billing'),
  'Top Items Sold Board',
  'Top Salesman Board',
  'Restock Items Board',
  'Sales return voucher',
  'Voucher/Invoice modification',
  'Purchase voucher',
  'Shortcut Barcode Printing',
  'Purchase return voucher',
  'Payment reminder feature',
  'Multi-store functionality',
  'Automated purchase reports',
  'Automated Item reports',
  'Automated PnL reports',
  'Downloadable reports',
  'List vs Card view',
  'Salesman wise billing',
  'Automated rounding off (upto ₹100)',
  'Item-wise discount setting',
  'Negative inventory billing',
  'Customer database management',
  'Custom barcode generation',
  'Supplier database management',
  'Custom users management',
  'Custom user app permissions',
  'Discount/Sale amount secret editor',
  'Credit Note functionality',
  'Exchange items functionality',
  'Multi-tax Purchase vouchering',
  'Individual barcode printing',
  'Credit sales setting',
  'Multiple owners in same company'
];

export const CATALOGUE_FEATURES = [
  'Online Catalogue',
  'Share on WhatsApp',
  'Receive Orders',
  'Online Payments',
  'Custom Domain',
  'Order Analytics',
  'Completed Sales Board',
  'Order Journey Tracking',
  'Daily Performance Board',
  'Top 5 Items Sold Board',
  'Restock Alerts',
  'Sales Report',
  'Customer Report',
  'Profit & Loss Report',
  'Item Report',
];